### Instructions

---

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the Logistic Regression Lessons

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

     https://colab.research.google.com/drive/1vis2e2aYid986w58hes8KTPxKcZFmFCW
     
2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project78** format.

4. Now, write your code in the prescribed code cells.

---

### Problem Statement

Nowadays everyone possesses one or more email accounts for digital communication. You may have observed that your mailbox classifies your relevant emails as primary emails and other irrelevant emails as spam. 

**Spam** emails are junk emails or unrequired emails. They may consist of advertisements, updated, and unwanted messages which are sent to the receivers without their permission. Hence, spam detection is one of the important problem statement in email and messaging servicing. 

In this project, you will create a model to classify the emails as **spam** or **not spam** using Logistic Regression.

---

### List of Activities

**Activity 1:** Analysing the Dataset

**Activity 2:** Train-Test Split

**Activity 3:** Normalisation of the Features

**Activity 4:** Logistic Regression - Model Training

**Activity 5:** Logistic Regression - Model Prediction and Evaluation

---

 
#### Activity 1:  Analysing the Dataset
 
Create a Pandas DataFrame for **Spambase** dataset using the below link. This dataset consists of the following 58 columns. Most of the columns represent frequencies of a particular word or character in the email:
 
 
|Column #|Attribute|Description|
|-|-|-|
|0 - 47|word_freq_WORD|The first 48 columns are the percentage|
|||of the frequencies of the particular word one column each|
||||
|48 - 53|word_freq_CHAR|The next 6 columns are the percentage of the frequencies of the|
|||particular special character like semi-colon (;), exclamation (!) one column each|
||||
|54|capital_run_length_average|average length of uninterrupted sequences of capital letters|
||||
|55|capital_run_length_longest|length of longest uninterrupted sequence of capital letters|
||||
|56|capital_run_length_total|sum of the length of uninterrupted sequences of capital letters|
||||
|57|email_type|denotes whether the email is spam (1) or not (0)|
 
 
 
 -  **Dataset Link:** https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/spambase.csv
   
- **Source:** UCI Library https://archive.ics.uci.edu/ml/datasets/Spambase
 
 
 
 
 
 
Print the first five rows of the dataset. Check for null values and treat them accordingly (if any).

In [11]:
# Import modules
import numpy as np
import pandas as pd
# Load the dataset
df = pd.read_csv('https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/spambase.csv')
# Print the first five rows of the DataFrame
df.head()

,0,0.64,0.64.1,0.1,0.32,0.2,0.3,0.4,0.5,0.6,...,0.41,0.42,0.43,0.778,0.44,0.45,3.756,61,278,1
0,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
1,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
2,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,1.85,0.00,0.00,1.85,0.00,0.00,...,0.00,0.223,0.0,0.000,0.000,0.000,3.000,15,54,1

Rename the last column of the DataFrame as target.

In [12]:
# Rename the last column as 'target'
df.rename(columns={"1":"target"}, inplace=True)

Print the information of the DataFrame to verify the above update.

In [13]:
# Print the dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4600 non-null   float64
 1   0.64    4600 non-null   float64
 2   0.64.1  4600 non-null   float64
 3   0.1     4600 non-null   float64
 4   0.32    4600 non-null   float64
 5   0.2     4600 non-null   float64
 6   0.3     4600 non-null   float64
 7   0.4     4600 non-null   float64
 8   0.5     4600 non-null   float64
 9   0.6     4600 non-null   float64
 10  0.7     4600 non-null   float64
 11  0.64.2  4600 non-null   float64
 12  0.8     4600 non-null   float64
 13  0.9     4600 non-null   float64
 14  0.10    4600 non-null   float64
 15  0.32.1  4600 non-null   float64
 16  0.11    4600 non-null   float64
 17  1.29    4600 non-null   float64
 18  1.93    4600 non-null   float64
 19  0.12    4600 non-null   float64
 20  0.96    4600 non-null   float64
 21  0.13    4600 non-null   float64
 22  0.14    4600 non-null   float64
 23  0.15    4600 non-null   float64
 24  0.16    4600 non-null   float64
 25  0.17    4600 non-null   float64
 26  0.18    4600 non-null   float64
 27  0.19    4600 non-null   float64
 28  0.20    4600 non-null   float64
 29  0.21    4600 non-null   float64
 30  0.22    4600 non-null   float64
 31  0.23    4600 non-null   float64
 32  0.24    4600 non-null   float64
 33  0.25    4600 non-null   float64
 34  0.26    4600 non-null   float64
 35  0.27    4600 non-null   float64
 36  0.28    4600 non-null   float64
 37  0.29    4600 non-null   float64
 38  0.30    4600 non-null   float64
 39  0.31    4600 non-null   float64
 40  0.33    4600 non-null   float64
 41  0.34    4600 non-null   float64
 42  0.35    4600 non-null   float64
 43  0.36    4600 non-null   float64
 44  0.37    4600 non-null   float64
 45  0.38    4600 non-null   float64
 46  0.39    4600 non-null   float64
 47  0.40    4600 non-null   float64
 48  0.41    4600 non-null   float64
 49  0.42    4600 non-null   float64
 50  0.43    4600 non-null   float64
 51  0.778   4600 non-null   float64
 52  0.44    4600 non-null   float64
 53  0.45    4600 non-null   float64
 54  3.756   4600 non-null   float64
 55  61      4600 non-null   int64
 56  278     4600 non-null   int64
 57  target  4600 non-null   int64
dtypes: float64(55), int64(3)
memory usage: 2.0 MB

**Q:** Are there any missing values?

**A:** no

---

#### Activity 2: Train-Test Split

You have to determine the effect of all the features on the 'target' variable. Thus, every column other than the `target` is the feature variable and `target` column is the target variable. 

**Steps:**

1. Create a list of all the features.

2. Split the "DataFrame" into features and target arrays using the features list.

3. Split the dataset into a training set and test set such that the training set contains 70% of the instances and the remaining instances will become the test set.

4. Reshape the target variable arrays into two-dimensional arrays by using `reshape(-1, 1)` function of the `numpy` module.

In [29]:
# Split the DataFrame into the train and test sets.
from sklearn.model_selection import train_test_split
# Import the module

 
# Create a features list 
features = list(df.columns)
features.remove('target')
target = df['target']
# Split the DataFrame into the train and test sets such that test set has 30% of the values.
x_train, x_test, y_train, y_test = train_test_split(df[features], target, test_size=0.30, random_state=42)
# Reshape target arrays to 2-dimensional array.
y_train = np.array(y_train).reshape(-1, 1)
y_test = np.array(y_test).reshape(-1, 1)

----

#### Activity 3: Normalisation of the Features
 
Get a descriptive analysis of the feature set and decide whether any normalisation is needed.

Describe the features for training data.

In [31]:
# Get the descriptive statistics for 'X_train'.
x_train.describe()

,0,0.64,0.64.1,0.1,0.32,0.2,0.3,0.4,0.5,0.6,...,0.40,0.41,0.42,0.43,0.778,0.44,0.45,3.756,61,278
count,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,...,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000
mean,0.105590,0.194068,0.284668,0.061326,0.315283,0.098438,0.106609,0.103963,0.088748,0.234516,...,0.033547,0.036403,0.142218,0.016734,0.268700,0.074947,0.044727,4.968248,52.542857,276.737888
std,0.306026,1.200963,0.516486,1.333192,0.691309,0.280005,0.373671,0.389894,0.255005,0.642719,...,0.274906,0.231370,0.288173,0.117969,0.892478,0.263572,0.368815,29.236502,216.614341,559.771635
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.583000,6.000000,34.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.067000,0.000000,0.000000,0.000000,0.000000,2.252500,14.000000,92.000000
75%,0.000000,0.000000,0.420000,0.000000,0.380000,0.000000,0.000000,0.000000,0.000000,0.150000,...,0.000000,0.000000,0.192000,0.000000,0.310000,0.048000,0.000000,3.628250,41.000000,260.000000
max,4.540000,14.280000,5.100000,42.810000,10.000000,5.880000,7.270000,11.110000,3.330000,18.180000,...,8.330000,4.187000,9.752000,4.081000,32.478000,6.003000,13.129000,1021.500000,9989.000000,10062.000000

Describe the features for the testing data.

In [30]:
# Get the descriptive statistics for 'X_test'.
x_test.describe()

,0,0.64,0.64.1,0.1,0.32,0.2,0.3,0.4,0.5,0.6,...,0.40,0.41,0.42,0.43,0.778,0.44,0.45,3.756,61,278
count,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000,...,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000,1380.000000
mean,0.102210,0.256913,0.271036,0.075036,0.305080,0.090051,0.132022,0.108478,0.093210,0.251014,...,0.027978,0.043669,0.131694,0.017551,0.269567,0.077880,0.043129,5.713512,51.302899,298.579710
std,0.303988,1.478609,0.474234,1.530927,0.626911,0.258923,0.429796,0.426271,0.327307,0.649769,...,0.309697,0.269704,0.223330,0.086214,0.599871,0.198743,0.545316,36.913490,131.034024,703.306895
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.600000,6.000000,37.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.059500,0.000000,0.000000,0.000000,0.000000,2.310500,16.000000,101.500000
75%,0.000000,0.000000,0.420000,0.000000,0.390000,0.000000,0.000000,0.000000,0.000000,0.170000,...,0.000000,0.000000,0.177000,0.000000,0.333250,0.061000,0.000000,3.852500,47.000000,287.250000
max,4.000000,14.280000,3.700000,42.730000,6.250000,3.570000,7.270000,5.880000,5.260000,11.110000,...,10.000000,4.385000,2.941000,1.449000,8.333000,3.125000,19.829000,1102.500000,2204.000000,15841.000000

**Q:** Does the data needs normalisation? Why?

**A:** Yes, it does


If the answer to the above question is **yes**, Normalise the data by calculating their $Z$-scores (or standard scaler) in the following code sections.

Define the Standard Normalisation function.

In [33]:
# Define the 'standard_scalar()' function for calculating Z-scores
def standard_scaler(series):
  new_series = (series - series.mean()) / series.std()
  return new_series

**Hint** 
$Z$-score for each value can be calculated by the following expression:

$$Z = \frac{X - \mu}{\sigma}$$

Where,


- $X$ is an observation 

- $\mu$ is the population mean

- $\sigma$ is the population standard deviation

Apply the normalisation function to the features of the training data.

In [36]:
# Apply the 'standard_scalar()' on X_train using apply() function and get the descriptive statistics of the normalised X_train
x_train_norm = standard_scaler(x_train)
x_train.describe()

,0,0.64,0.64.1,0.1,0.32,0.2,0.3,0.4,0.5,0.6,...,0.40,0.41,0.42,0.43,0.778,0.44,0.45,3.756,61,278
count,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,...,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000
mean,0.105590,0.194068,0.284668,0.061326,0.315283,0.098438,0.106609,0.103963,0.088748,0.234516,...,0.033547,0.036403,0.142218,0.016734,0.268700,0.074947,0.044727,4.968248,52.542857,276.737888
std,0.306026,1.200963,0.516486,1.333192,0.691309,0.280005,0.373671,0.389894,0.255005,0.642719,...,0.274906,0.231370,0.288173,0.117969,0.892478,0.263572,0.368815,29.236502,216.614341,559.771635
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.583000,6.000000,34.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.067000,0.000000,0.000000,0.000000,0.000000,2.252500,14.000000,92.000000
75%,0.000000,0.000000,0.420000,0.000000,0.380000,0.000000,0.000000,0.000000,0.000000,0.150000,...,0.000000,0.000000,0.192000,0.000000,0.310000,0.048000,0.000000,3.628250,41.000000,260.000000
max,4.540000,14.280000,5.100000,42.810000,10.000000,5.880000,7.270000,11.110000,3.330000,18.180000,...,8.330000,4.187000,9.752000,4.081000,32.478000,6.003000,13.129000,1021.500000,9989.000000,10062.000000

Apply the normalisation function to the features of the test data.

In [37]:
# Apply the 'standard_scalar()' on X_test and get the descriptive statistics of the normalised X_test
x_test_norm = standard_scaler(x_test)
x_test_norm.describe()

,0,0.64,0.64.1,0.1,0.32,0.2,0.3,0.4,0.5,0.6,...,0.40,0.41,0.42,0.43,0.778,0.44,0.45,3.756,61,278
count,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,...,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03,1.380000e+03
mean,-2.767512e-17,-2.059544e-17,3.089316e-17,1.287215e-18,2.059544e-17,2.574430e-18,2.445709e-17,6.178632e-17,-1.029772e-17,-1.287215e-17,...,2.574430e-18,1.029772e-17,4.119088e-17,1.802101e-17,3.604202e-17,-5.406303e-17,-2.574430e-18,-2.574430e-18,2.059544e-17,-2.188266e-17
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-3.362312e-01,-1.737532e-01,-5.715240e-01,-4.901358e-02,-4.866398e-01,-3.477892e-01,-3.071728e-01,-2.544822e-01,-2.847794e-01,-3.863134e-01,...,-9.034086e-02,-1.619142e-01,-5.896831e-01,-2.035800e-01,-4.493757e-01,-3.918651e-01,-7.908990e-02,-1.276908e-01,-3.838919e-01,-4.231150e-01
25%,-3.362312e-01,-1.737532e-01,-5.715240e-01,-4.901358e-02,-4.866398e-01,-3.477892e-01,-3.071728e-01,-2.544822e-01,-2.847794e-01,-3.863134e-01,...,-9.034086e-02,-1.619142e-01,-5.896831e-01,-2.035800e-01,-4.493757e-01,-3.918651e-01,-7.908990e-02,-1.114365e-01,-3.457339e-01,-3.719283e-01
50%,-3.362312e-01,-1.737532e-01,-5.715240e-01,-4.901358e-02,-4.866398e-01,-3.477892e-01,-3.071728e-01,-2.544822e-01,-2.847794e-01,-3.863134e-01,...,-9.034086e-02,-1.619142e-01,-3.232618e-01,-2.035800e-01,-4.493757e-01,-3.918651e-01,-7.908990e-02,-9.218883e-02,-2.694178e-01,-2.802187e-01
75%,-3.362312e-01,-1.737532e-01,3.141144e-01,-4.901358e-02,1.354583e-01,-3.477892e-01,-3.071728e-01,-2.544822e-01,-2.847794e-01,-1.246820e-01,...,-9.034086e-02,-1.619142e-01,2.028644e-01,-2.035800e-01,1.061605e-01,-8.493601e-02,-7.908990e-02,-5.041549e-02,-3.283802e-02,-1.610920e-02
max,1.282220e+01,9.483975e+00,7.230529e+00,2.786217e+01,9.482882e+00,1.344008e+01,1.660781e+01,1.353957e+01,1.578578e+01,1.671207e+01,...,3.219932e+01,1.609668e+01,1.257914e+01,1.660343e+01,1.344195e+01,1.533196e+01,3.628331e+01,2.971235e+01,1.642854e+01,2.209906e+01

---

#### Activity 4: Logistic Regression - Model Training 

Implement Logistic Regression Classification using `sklearn` module to estimate the values of $\beta$ coefficients in the following way:

1. Deploy the model by importing the `LogisticRegression` class and create an object of this class.
2. Call the `fit()` function on the Logistic Regression object and print score using the `score()` function.
3. Print the $\beta$ coefficient values.

In [38]:
# Deploy the 'LogisticRegression' model using the 'fit()' function.
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(n_jobs = -1)
log_reg.fit(x_train_norm, y_train)
log_reg.score(x_train_norm, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.9357142857142857

Get the beta coefficients for the features using the model object trained in the above code.

In [43]:
# Print the beta coefficient values
print(log_reg.coef_)

[[-0.07136353 -0.18809122  0.03227679  0.82515854  0.49370386  0.15499401
   0.9376552   0.3885888   0.29549879  0.06133681 -0.06908977 -0.15980028
  -0.014238    0.01461507  0.23176417  1.12930449  0.46115314  0.02445538
   0.23099334  0.38109803  0.23660276  0.33931187  0.87855021  0.12543899
  -2.62002691 -1.18078792 -4.61219019  0.18365606 -1.0490246  -0.16578289
  -1.2640231  -0.21002441 -0.63112108 -0.06179556 -1.28584947  0.22755189
   0.01686322 -0.17333969 -0.31219422 -0.1173059  -1.35380234 -1.65417694
  -0.29855825 -1.07144395 -0.90421721 -1.27106526 -0.18572137 -0.95402961
  -0.3487004  -0.03990328 -0.10581458  0.22678643  1.2141685   0.86261082
  -0.21863815  0.95082428  0.56678385]]

----

#### Activity 5: Logistic Regression - Model Prediction and Evaluation

Predict the values for both training and test sets by calling the `predict()` function on the Logistic Regression object.

In [47]:
# Make predictions on the test dataset by using the 'predict()' function.
train_pred = log_reg.predict(x_train_norm)
test_pred = log_reg.predict(x_test_norm)

Also, display the confusion matrix.

In [49]:
# Display the results of confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix
print(f'Train confusion matrix: \n {confusion_matrix(y_train, train_pred)} \n Test confusion matrix: \n {confusion_matrix(y_test, test_pred)}')

Train confusion matrix:
 [[1910   75]
 [ 132 1103]]
 Test confusion matrix:
 [[762  41]
 [ 92 485]]

**Q:** What is the positive outcome out of both the labels?

**A:** 

**Q:** Write the count of True Positives and True Negatives?

**A:** True positives for train: 1910
True negatives for train: 1103

True positives for test: 762
True negatives for test: 485


Print the classification report values to evaluate the accuracy of your model.

In [50]:
# Display the results of classification_report
print(classification_report(y_train, train_pred))
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95      1985
           1       0.94      0.89      0.91      1235

    accuracy                           0.94      3220
   macro avg       0.94      0.93      0.93      3220
weighted avg       0.94      0.94      0.94      3220

              precision    recall  f1-score   support

           0       0.89      0.95      0.92       803
           1       0.92      0.84      0.88       577

    accuracy                           0.90      1380
   macro avg       0.91      0.89      0.90      1380
weighted avg       0.90      0.90      0.90      1380

**Q** Write the f1-score of both labels?

**A:** 0.92, 0.95

-----

### Submitting the Project

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project77**) of the notebook will get copied.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project77** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---